### ISSUE TITLE
Can you customize the rules?

### ISSUE THREAD

**Issue by runhwguo** [x1angli/convert2utf#3]
In virsual stduio, cpp,i want it's chatset can be utf-8-sig
and in java ,i want to be utf-8, without bom.

**Comment by runhwguo** [comment]
for example, i want to check c cpp oc java source.
 if extension != 'java' and encoding.upper() == 'UTF-8-SIG':
    return

**Comment by x1angli** [comment]
Hi runhwguo,
Thanks for your feedback. 
Sure, we can certainly do that. Before changing the rule , could you please provide further information regarding the necessity of enforcing utf-8-sig for c/cpp files? Shall we do this in all kinds of situations ?  or we just do this for certain cases?

**Comment by runhwguo** [comment]
In visual studio, for windows project, if convert non-utf-8 to utf-8 without bom, it will lead to failure of compilation c/c++, because vs needs bom, but in android stduio, require java without bom to compile successfully.
in my view, c/c++/oc convert to utf-8-sig and java converts to utf-8.

We also need to consider the Chardet library, it will return file charset and charset confidence, is not it?   In the course of my practice, i find some encoding is compatible when the source file is mostly code with english letter, that's to say, hardly any non-ascii letter, in this case some special letter will be converted incorrectly, for example.
// 2015年 created it
#include <stdio.h>

int main() {
    pirntf("just for example.");
}

in this case, the character of '年' after convertion will be messy code.So I think this need to define a threshold value to optimize it.
e.g.
   if detect_confidence >= 0.8:
       pass
otherwise, in a large productive project, it will make a bit of trouble.


On Weekend, I will create a pr to your useful repository.

**Comment by x1angli** [comment]
@runhwguo thanks for your input. 

> because Visual Studio needs bom

First, we need to know whether C/C++ compilers (e.g. GCC) on Linux require BOM. Otherwise, if any compiler requires that BOM should be removed in all C/C++ files, then we have to make our encoding rule more flexible and leave the option to end users. Does GCC and other C compilers require BOM? 

Secondly, do old versions  (e.g. VS2008) and new versions (e.g. VS2015) of VS behave the same way in that they both require BOM? (alternatively, new versions of VS may tolerate C/C++ files w/o BOM)

**Comment by x1angli** [comment]
> So I think this need to define a threshold value to optimize it.

In your case, how much was the confidence level returned by chardet? 


> otherwise, in a large productive project, it will make a bit of trouble.

End users must be cautious in a large production environment. Aggressive actions like this must be tested  in dev env, or in an isolated sandbox first ,  rather than directly in production environment. So, in addition to setting up a confidence threshold, we have to highlight such warning in our readme doc.

**Comment by x1angli** [comment]
@runhwguo 
i just updated the code. Per your request: 



* Convert all .c and .cpp files to UTF-8 with BOMs. This action will also __add__ BOMs to existing UTF-encoded files. 
    
    `python cvt2utf.py "/path/to/your/visual/studio/repo" -b -u --exts c cpp`
    

* Convert all .php, .js, .java, .py files to UTF-8 encoding. Meanwhile, those BOMs from existing UTF-encoded files will be __removed__ . 

    `python cvt2utf.py "/path/to/your/android/linux/repo" -u --exts php js java py`

I haven't update the PyPI yet. So please pull the updated source code from Github and test it. 

Please let me know if it works or not. Thanks!
