### ISSUE TITLE
error on recognizing some UTF-16 and UTF files

### ISSUE THREAD

**Issue by UVJkiNTQ** [x1angli/convert2utf#6]
**Describe the bug**
I use the tool to convert .cue and .log files.
I discovered problem with some UTF-8 encoded cue files and many UTF-16 encoded log files.
Some UTF-8 encoded files do not transcoding well and still have problem in mapping.
UTF-16 encoded log files are recognized as latin_1 encoded.

Example is attach. 
.bak is the original fils.
[error.zip](https://github.com/x1angli/cvt2utf/files/4359386/error.zip)

**Comment by x1angli** [comment]
@UVJkiNTQ 
Thank you for your feedback along with detailed information

- the `SW-030GAMERS.cue` file in your zip, sorry but that file looks good. is there any problem?

- the `SW-030GAMERS.log` file. Yes it's totally scrambled. 

The reason: cvt2utf relies on a 3rd-party tool called `chardet` to detect codc/charsets. `chardet` is generally good, but it has a cryptic and confusing probabilistic model, which makes the codec erroneously detected in certain cases. In order to ameliorate this problem, our `cvt2utf` uses some tricks. However, these tricks may break or fail in other cases...

At this moment, you can follow the instruction below to temporarily solve this flaw

1. `git clone` or download the source code
2. go to Line 20 of [cvt2utf/main.py](https://github.com/x1angli/cvt2utf/blob/8a8197e6aeda6f2eab865676279ff09c78376640/cvt2utf/main.py#L20) 
3. drop the `latin-1`, so as to make it look like `'codec_chain': ['ascii', 'utf_8_sig', 'chardet'],`
4. go to terminal / cmd, `cd` to the cvt2utf folder (the upper cvt2utf folder, not the lower sub-folder), run `python3 -m cvt2utf.main convert "./error" -i log` (change the path to your path)

As a result, it can be correctly recognized as UTF-16 and transcoded to Latin-1. I tried on my machine and the generated SW-030GAMERS.log looks good. 
let me know if you run into any further problem

Note 1: cvt2utf8 is not intended for general users, instead, it aims at coding-savvy users . Though I've tried my best to make it easy to use, yet still, users are expected to understand how it works.........

Note 2: dropping `latin-1` may work in this case, but may break things in other cases....

**Comment by UVJkiNTQ** [comment]
That cue seems good. I am sorry for that. It just looks bad in nano.
I will try the workaround.
Thanks.
